### ISSUE TITLE
httpPost not working

### ISSUE THREAD

**Issue by Rimobul** [AprilBrother/cactus-micro-r2#1]
Hello, I have tried your httpPost example, but it is not working. My localhost address is 192.168.1.8 and my server is TestServer/Default.aspx, so I have rewritten the header like this: 

``` c++
#define HOST         "192.168.1.8"
#define HOST_NAME    "localhost"

#define DEBUG         1

#define REQ_PREFIX    "POST /TestServer/Default.aspx\r\n" \
    "Host: " HOST_NAME "\r\n" \
    "Accept: *" "/" "*\r\n" \
    "Content-Length: "
```

After the first connection, I get:

OKConnected AP success
AT+CIFSR

AT+CIFSR

+CIFSR:STAIP
AT+CIFSR

+CIFSR:STAIP
timer reset: 13387
Sending data...
AT+CIPSTART="TCP","192.168.1.8",8080
AT+CIPSTART="TCP","192.168.1.8",8080

but then after that I keep getting

_ERRORNot connected
AT+CIPCLOSE
timer reset: 25984
Sending data...
AT+CIPSTART="TCP","192.168.1.8",8080
AT+CIPSTART="TCP","192.168.1.8",8080_

Plus, the debug writes port 8080, however, my server runs on port 80. But I cannot see anywhere the definition of the port used. Could you help me with resolving the issue?

**Comment by volca** [comment]
Hi, 

Please check the line, here's a '8080'

https://github.com/AprilBrother/cactus-micro-r2/blob/master/libraries/CactusMicro/examples/httpPost/httpPost.ino#L169

**Comment by Rimobul** [comment]
This is so embarassing. I was convinced it is just a debug log that I did not even try to change it. Thank you very much, everything now works properly.

**Comment by volca** [comment]
Great! So I closed the issue. Thank you.
