### ISSUE TITLE
httpPost not sending anything.

### ISSUE THREAD

**Issue by netcyrax** [AprilBrother/cactus-micro-r2#2]
I am trying to test my newly received Cactus Micros using the httpPost example. Unfortunately, although i am getting success messages, it doesn't seem to sending anything. I am using the RequestBin service to test the post request. Here is a snippet of the configuration:

```
#define HOST         "54.243.91.32"
#define HOST_NAME    "requestb.in"

#define DEBUG         1

#define REQ_PREFIX    "POST /18wrdiy1\r\n" \
    "Host: " HOST_NAME "\r\n" \
    "Accept: *" "/" "*\r\n" \
    "Content-Length: " 
```

The success messages that i am getting in the monitor:

```
CONNECT

OKConnected
AT+CIPSEND=136

AT+CIPSEND=136


OK
>Done:
AT+CIPSEND=136


OK
>
ready to send:
 POST /18wrdiy1
Host: requestb.in
Accept: */*
Content-Length: 8
Content-Type: text/html; charset=UTF-8
Connection: close

test=123
SEND OKAT+CIPCLOSE
timer reset: 60350
Sending data...
AT+CIPSTART="TCP","54.243.91.32",80
AT+CIPSTART="TCP","54.243.91.32",80
```

**Comment by volca** [comment]
The espduino library works perfectly with Cactus Micro Rev2. You can try the firmware for rest api request. 

Please refer [the wiki](http://wiki.aprbrother.com/wiki/Cactus_Micro_R2_Tutorial#For_espduino_library_from_Tuan_PM) for more information.

**Comment by netcyrax** [comment]
Thank you for your reply. I have tried the espduino firmware and the http post request work fine now. I wasted many hours trying to figure out why the httpPost example wasn't working. If it is not working with the built-in esp firmware please let users know and urge them to use the espduino (or even better ship the Cactus Micro with espduino if possible!)

**Comment by volca** [comment]
Did you buy the Cactus Micro rev1 or rev2? Could you please take a photo for the board?

Thank you.

**Comment by netcyrax** [comment]
I ordered the Cactus Micro rev2 (from Tindie). Here it is:
![cactus](https://cloud.githubusercontent.com/assets/1542151/11058591/c8479290-878b-11e5-8912-e3f9fe332eee.jpg)

**Comment by volca** [comment]
Thank you for your response.

We will pre-upload the espduino firmware to esp8266 next batch.

**Comment by netcyrax** [comment]
Great! Love your direct communications with your customers!
