### ISSUE TITLE
Power managment

### ISSUE THREAD

**Issue by MathGon** [AprilBrother/cactus-micro-r2#3]
Thank for your nice repo about the genious Cactus micro. Is there a way to improve energy consumption, sleeping the device between to POST?

**Comment by volca** [comment]
I think here's some tips.
- Power the board through VCC(must be 3.3V) directly(bypassing the LDO)
- Check [the article about power saving for 32u4](https://harizanov.com/2013/02/power-saving-techniques-on-the-atmega32u4/).
- disable esp8266 module after POST
