### ISSUE TITLE
Baud Rate

### ISSUE THREAD

**Issue by dda** [AprilBrother/cactus-micro-r2#5]
In the setup of one of the `esp8266Programmer` example, code says `Serial[1].begin(115000);`. I suppose this is a typo..?

Did you try that code?? Pretty sure that wouldn't work in the real world. [Hint: I tried and it doesn't]

Also, depending on the example, the baud rate goes from 9600 to 115200. Which begs the question: _What is the default baud rate for the ESP8266?_

**Comment by volca** [comment]
it should be 115000 not 115200. because  ATMega 32U4 runs a inaccurate rate with crystal for high baud rate 115200. 

Do  you buy cactus micro recently? Please check this [link](http://wiki.aprbrother.com/wiki/Cactus_Micro_Starter_Guide) also.

**Comment by dda** [comment]
Thanks. I bought my cactus a while ago but only got around to playing with it today.
I have indeed looked at the wiki, and the baud rates are all over the place in the examples.
