### ISSUE TITLE
cactus says nothing more ....

### ISSUE THREAD

**Issue by hanshaze** [AprilBrother/cactus-micro-r2#6]
i have no idea what happened, but somehow the hardware is no longer recognized by my laptop.... 
the ide says NO DONGLE CONNECTED.....so it has nothing to work with.....
how can i unbrick? 
hope you have something like a solution for me ^^

best regards

**Comment by hanshaze** [comment]
can be closed, i got it!

**Comment by volca** [comment]
Hi,

Did you resolve the issue?

**Comment by hanshaze** [comment]
Yes, you have to reset via Magnet for one time while reflashing! 
#problemsolved

**Comment by volca** [comment]
thanks for confirm this!
