### ISSUE TITLE
Cannot Flash the ESP8266 via the Cactus_Micro_R2_as_ESP8266_programmer Sketch

### ISSUE THREAD

**Issue by spaceman5** [AprilBrother/cactus-micro-r2#7]
Hi

I have a Cactus Micro rev2 that I purchased from Seeedstudio several years ago..

I am able to program the ATmega32U4,
but am not able to program the ESP8266 via the ATmega32U4, with the sketch that is offered here:
https://github.com/AprilBrother/cactus-micro-r2/blob/master/libraries/CactusMicro/examples/esp8266Programmer/esp8266Programmer.ino

What should I do?

I also tried running the searchBaudRate.ino sketch:
https://github.com/AprilBrother/cactus-micro-r2/blob/master/libraries/CactusMicro/examples/searchBaudRate/searchBaudRate.ino

But the result I get is "not found."

Please help how to succeed in re-flashing the ESP8266 that is on the Cactus Micro rev2..

Thank you

**Comment by volca** [comment]
Could you please show a photo about the Cactus Micro? I want to check the hardware model.

**Comment by spaceman5** [comment]
Hi

Of course:
Top:
https://i.postimg.cc/WbbHwC3W/DSC-0006.jpg

Bottom:
https://i.postimg.cc/nzG3vGtf/DSC-0014.jpg

Thank you for your help

**Comment by volca** [comment]
Please check [the wiki](https://wiki.aprbrother.com/en/How_to_made_Cactus_Micro_R2_as_ESP8266_programmer.html). Did you use the modified esptool to program ESP8266?

**Comment by spaceman5** [comment]
Hi volca

Indeed I read that Wiki page when I tried to flash the ESP8266..

>Did you use the modified esptool to program ESP8266?
Actually no,
I used the latest esptool.py - https://github.com/espressif/esptool
It is working for me with all my ESP8266 boards and modules,
except with the Cactus Micro rev2..

Where can I download the modified one that you mention?

And btw, in the Wiki page another tool is mentioned - the NodeMCU Flasher,
so which one to use?
(does the tool really matter? If it's an ESP8266, and if the program is relaying the data,
then why would the tool matter?)

**Comment by spaceman5** [comment]
Hi volca

Indeed I read that Wiki page when I tried to flash the ESP8266..

Regarding: Did you use the modified esptool to program ESP8266?

Actually no,
I used the latest esptool.py - https://github.com/espressif/esptool
It is working for me with all my ESP8266 boards and modules,
except with the Cactus Micro rev2..

Where can I download the modified one that you mention?

And btw, in the Wiki page another tool is mentioned - the NodeMCU Flasher,
so which one to use?
(does the tool really matter? If it's an ESP8266, and if the program is relaying the data,
then why would the tool matter?)

**Comment by volca** [comment]
please check [the link for esptool](https://github.com/AprilBrother/esptool). The latest esptool uses a very large flash block so 32u4 can't handle it proper. We fix it with [the commit](https://github.com/AprilBrother/esptool/commit/1bf0c227c927099632c7b0a7cfc96e5fb8d0ed2e)

**Comment by spaceman5** [comment]
Oh, I see.
Really interesting, OK I will run the modified esptool and see If I now succeed.

BTW, what about the NodeMCU Flasher that is mentioned in the Wiki page?
Is it good too, and works with a small block size?

**Comment by volca** [comment]
the nodemcu flasher works fine with windows. You can give it a try also

**Comment by spaceman5** [comment]
Thank you veryu much volca.

I tried NodeMCU's flasher, and indeed now the flashing completed.

But unfortunately, it seems that the firmware is not running well.

I created a small program to send an "AT+GMR" command to the ESP8266 chip,
(ATmega32U4's Leg 12 set to High, for Communication Mode,
and ATmega32U4's Leg 13 set to High, to Enable the ESP8266 chip),
and no matter what BaudRate I try, I only get jibrish.

When I try the Bootloader's BaudRate (74880), when still in Communication mode and not Programming mode (meaning Leg 12 set to High),
this is what I get:

https://i.postimg.cc/ZKvS4qBd/Almost.png


I tried every possible BaudRate, from 300 to 115200, including 115000...


Any idea what I am still missing, in order to make it succeed?

**Comment by spaceman5** [comment]
Thank you very much volca.

I tried NodeMCU's flasher, and indeed now the flashing completed.

But unfortunately, it seems that the firmware is not running well.

I created a small program to send an "AT+GMR" command to the ESP8266 chip,
(ATmega32U4's Leg 12 set to High, for Communication Mode,
and ATmega32U4's Leg 13 set to High, to Enable the ESP8266 chip),
and no matter what BaudRate I try, I only get jibrish.

When I try the Bootloader's BaudRate (74880), when still in Communication mode and not Programming mode (meaning Leg 12 set to High),
this is what I get:

https://i.postimg.cc/ZKvS4qBd/Almost.png

I tried every possible BaudRate, from 300 to 115200, including 115000...

Any idea what I am still missing, in order to make it succeed?

**Comment by spaceman5** [comment]
I should mention that I tried several different Firmwares, older and newer,
and I also tried with QIO (like the wiki page says) and with DIO even..

**Comment by volca** [comment]
You should try to erase the entire flash first. The flash size should be 1MB.

**Comment by spaceman5** [comment]
OK I tried it now.

I took the blank,bin file, and replicated it till it became exactly 1048576Bytes.
It contains only FFh.

I flashed it, at address 00000h, and the flashing completed.

Then, trying to communicate with the ESP8266, only gives the Bootloader message,
but not the "ready." that should come after it.

Also no response from the ESP8266 module for AT commands, like AT+GMR.


I think that my last attempt will be to directly connect to the ESP8266 module,
completely bypassing the ATmega32U4.

I can connect to the ESP8266 Module's TX+RX legs, using an FTDI Adapter,
but my only problem is that those legs are still connected to the ATmega32U4's Serial Port (Serial1).

So my idea, is to load a program on the ATmega32U4, that will set the relevant 2 legs (D1 and D2) as Input legs,
and will not call the Serial1.begin() method.

Thus, while the ESP8266 remains physically connected to the ATmega32U4,
the ATmega32U4's 2 legs will not output any votage there, and so the ATmega32U4 will not interfere, and there will be no short circuit during the flashing process.

What do you think?
Is this a good idea, or is there any problem with it that I do not see?

**Comment by spaceman5** [comment]
OK I tried it now.

I took the blank,bin file, and replicated it till it became exactly 1048576Bytes.
It contains only FFh.

I flashed it, at address 00000h, and the flashing completed.

Then, trying to communicate with the ESP8266, only gives the Bootloader message,
but not the "ready." that should come after it.

Also no response from the ESP8266 module for AT commands, like AT+GMR.

I think that my last attempt will be to directly connect to the ESP8266 module,
completely bypassing the ATmega32U4.

I can connect to the ESP8266 Module's TX+RX legs, using an FTDI Adapter,
but my only problem is that those legs are still connected to the ATmega32U4's Serial Port (Serial1).

So my idea, is to load a program on the ATmega32U4, that will set the relevant 2 legs (D0 and D1) as Input legs,
and will not call the Serial1.begin() method.

Thus, while the ESP8266 remains physically connected to the ATmega32U4,
the ATmega32U4's 2 legs will not output any votage there, and so the ATmega32U4 will not interfere, and there will be no short circuit during the flashing process.

What do you think?
Is this a good idea, or is there any problem with it that I do not see?

**Comment by volca** [comment]
Did you flash the AT firmware? please give me the link. I will try it with my Cactus Micro.

> So my idea, is to load a program on the ATmega32U4, that will set the relevant 2 legs (D0 and D1) as Input legs,
> and will not call the Serial1.begin() method.

it's a good idea. Did you try?

**Comment by spaceman5** [comment]
Yes, I flashed the AT Firmware..
I tried 2 versions.. v1.6.2, and also an old one.

Regarding a link,
instead of a link, can I give you the exact .BIN file that I use?


Regarding directly connecting to the ESP8266's Serial Port,
I will write in a separate post here.. Please see the next post after this.

**Comment by spaceman5** [comment]
I wanted to try it, but before trying I decided to do some simple test,
to verify that indeed I will not make a short circuit when connecting to ESP8266's 2 serial legs.


So what I did is this:

I have a 2-Ch Scope, and I connected 1 channel to the TXO leg of the Cactus Micro module,
and the second channel to the RXI leg.

On the scope, the TX leg is shown in Blue, and the RX leg in Yellow.

The understanding is that those are the 2 legs of the ATmega32U4's Serial1, connected to the ESP8266's Serial Port.

Then:


Test #1:
I ran a program that its loop contains nothing, not sending anything,
and wanted to see that indeed I see nothing on the Serial Port.

The result:
https://i.postimg.cc/Dz8qR6vt/1-Not-Sending-Data.png

Both legs show 3.6v (and not 3.3v for some reason), meaning "1", probably a pull-up which is part of the Serial UART.
So the test is good, compete silence on the port.


Test #2:
I ran a program that it's loop has this:
Serial1.write(0xFA);
It simply continuously sends Data, on Serial1, to the ESP8266.

The result:
https://i.postimg.cc/SswFcgRq/2a-Sending-Data.png

As can be seen, the data that I am sending is well shown there,
and the Yellow channel (RX) shows nothing.

Just to verify, I turned the TX (blue) channel Off on the scope, in order to see only the RX (yellow) channel, and here is the result:
https://i.postimg.cc/vB5XShXG/2b-Sending-Data-TX-is-Removed-to-See-Only-RX.png

Complete silence on the RX leg, which is what we want to see.


I then wanted to see data being sent back, on this serial port.
I cannot successfully execute AT commands on the ESP8266 module, since as written, my flashings which succeed in flashing, do not succeed in running.
So I remembers that the boot message upon reset, sends a little bit of text to the Serial Port.
So I reset the module, which causes the ESP8266 to send this small text.

And the graph:
https://i.postimg.cc/cHQ6z9j1/3a-Receiving-Data-from-ESP8266-Boot-Message.png

As expected, we see action on the RX line.



So far this is good,
it shows me that:
1) The TXO and RXI legs on the Cactus Micro module that I connected to, are indeed the right legs that I need for the relevant Serial Port connection (ATmega32U4Serial1<->ESP8266)
2) No other data is on this connection






Then, I made another small test:
Instead of the line:
Serial1.write(0xFA);
I put this line in the loop():
Serial.write(0xFA);
(Serial without 1.. meaning the Serial Port that goes to the USB).
While I am still connected to Serial1's legs.

The expectation is to see nothing now, because it's a different Serial Port, that we do not listen to, with the scope.

The result:
https://i.postimg.cc/26pNZHVY/6-Sending-Data-on-Serial-instead-of-Serial1.png

Complete silence, as it should be,
showing the 2 serial ports are separate.


On this stage I should've been quite satisfied and do the direct flashing that I planned to do,
but then I discovered a small surprise..

Will write it in the next post

**Comment by spaceman5** [comment]
What was the surprise?

I pressed Ctrl-U (upload) on my Arduino IDE, to upload a sketch to the ATmega32U4,
and to my surprise, this is what I see on the scope:

https://i.postimg.cc/6pm06qQ2/5a-Problem-this-is-how-an-Upload-looks-why-does-it-appear-on.png

The whole upload duration, is shown in the scope.

Allow me to remind:
The scope is still connected to Serial1..
That's the connection between the ATmega32U4 and the ESP8266,
the scope is not connected to the ATmega32U4<->USB connection..

So why do I see action during upload?


Some more screenshots of this:

https://i.postimg.cc/Y0D4N4ZQ/5b-This-is-the-Upload-with-the-RX-Graph-Moved-Down.png
Here I moved the Yellow graph (RX) down, so we can see both the blue and the yellow graphs separately, instead of 1 on top of each other:


When I saw this, I did not move on,
I should not see any activity on the Serial1 port, when doing an upload to the ATmega32U4..


Do you maybe understand what is happening here?

**Comment by volca** [comment]
I suggest you flash [the ai-thinker-v1.1.1.bin](https://i1.aprbrother.com/ai-thinker-v1.1.1.bin) because it works years ago. Does the v1.6.2 firmware work with module with 1MB flash?

**Comment by spaceman5** [comment]
Hi volca
Thank you for that bin file, and sorry for my delay.
I flashed the ai-thinker-v1.1.1.bin now, and like the other bins I have, NodeMCU's Flasher flashed it well.

It might be that the flashing works well,
but my communication afterwards, via the ATmega32U4's help, has some issue..

In my tester program, after flashing, I set Leg 12 to High (for Communication mode, instead of Programming mode),
and Leg 13 to High (For Enabling the ESP8266 module).

I then do:
Serial1.begin(74880);
Serial .begin(115200);

I chose 74880, in order to see the Bootloader message.
I get this:
" ets Jan  8 2013,rst cause:1, boot mode:(3,6)

load 0x40100¡µ:M|Kpý"

The bootloader message looks OK,
and I suspect that the small Jibrish in the end, is the "ready." message that we should see.
(because we're now in Communication mode).

The problem is,
that no matter what BaudRate I try,
I can't get to have the "ready." string displayed..

What BaudRates do you put in Serial1.begin(#) and Serial .begin(#)?

**Comment by volca** [comment]
I usually put a very low baud rate such as 9600 in it.  see [the line](https://github.com/AprilBrother/cactus-micro-r2/blob/master/libraries/CactusMicro/examples/hardwareSerialMonitor/hardwareSerialMonitor.ino#L6)

Please also try to replace the usb cable to a shorter one to get better power supply.

**Comment by spaceman5** [comment]
Thank you.
I tried that exact sketch, changing nothing in it,
and this is what I get:

https://i.postimg.cc/hvj2x7vX/1.png

Trying to type any AT Command, such as "AT+GMR", returns nothing,
mostlikely meaning the ESP8266 is not getting the characters right, but in jibrish.

I don't know, maybe there is a problem with my board?

Also quite weird, please see this:
https://i.postimg.cc/SQ36VPtT/2.png

When changing the SerialMonitor's BaudRate to 115200 (before opening it),
still shows the println() lines to "Serial" correctly,
that's espite the fact that Serial was initialized with ".begin(9600)"..

When Arduino IDE's Serial Window is set to 115200, we should not see the text well,
yet we do.

I cannot to explain it.

Should I simply give up on this board? :/

**Comment by volca** [comment]
emm. it's very strange but I have no better idea.

**Comment by spaceman5** [comment]
I see.
I really thank you for all your help, it was quite a surprise to get support for something bought several years ago, thank you so much.

Bye
